package cn.music.audioworkshop.ui.theme

import androidx.compose.ui.graphics.Color

data class AppThemeSpec(
    val name: String,
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val accent: Color,
    val onAccent: Color,
    val background: Color,
    val surface: Color,
    val onSurface: Color,
    val outline: Color,
)

object ThemeCatalog {
    val themes: List<AppThemeSpec> = listOf(
        AppThemeSpec(
            name = "元气橙",
            primary = Color(0xFFDD5C00),
            onPrimary = Color(0xFF151515),
            primaryContainer = Color(0xFFFFE6CC),
            onPrimaryContainer = Color(0xFF4A2500),
            accent = Color(0xFF24ABE8),
            onAccent = Color(0xFF151515),
            background = Color(0xFFFFFFFF),
            surface = Color(0xFFFFF9F5),
            onSurface = Color(0xFF241711),
            outline = Color(0xFFEADED9),
        ),
        AppThemeSpec(
            name = "晴空蓝",
            primary = Color(0xFF0086DD),
            onPrimary = Color(0xFF151515),
            primaryContainer = Color(0xFFD6EFFF),
            onPrimaryContainer = Color(0xFF002F55),
            accent = Color(0xFFE76C2B),
            onAccent = Color(0xFF151515),
            background = Color(0xFFFFFFFF),
            surface = Color(0xFFF6FBFF),
            onSurface = Color(0xFF111C26),
            outline = Color(0xFFD9E3EB),
        ),
        AppThemeSpec(
            name = "薄荷青",
            primary = Color(0xFF009A7B),
            onPrimary = Color(0xFF151515),
            primaryContainer = Color(0xFFC9F7E9),
            onPrimaryContainer = Color(0xFF003D2E),
            accent = Color(0xFFA672DC),
            onAccent = Color(0xFF151515),
            background = Color(0xFFFFFFFF),
            surface = Color(0xFFF5FCFA),
            onSurface = Color(0xFF0D1E1A),
            outline = Color(0xFFD8E5E1),
        ),
        AppThemeSpec(
            name = "星云紫",
            primary = Color(0xFF8F5DD6),
            onPrimary = Color(0xFF000000),
            primaryContainer = Color(0xFFF2E9FF),
            onPrimaryContainer = Color(0xFF37134F),
            accent = Color(0xFF00ABA4),
            onAccent = Color(0xFF151515),
            background = Color(0xFFFFFFFF),
            surface = Color(0xFFFBF9FF),
            onSurface = Color(0xFF1C1825),
            outline = Color(0xFFE3DFEA),
        ),
        AppThemeSpec(
            name = "桃桃粉",
            primary = Color(0xFFD14693),
            onPrimary = Color(0xFF101010),
            primaryContainer = Color(0xFFFFE1F3),
            onPrimaryContainer = Color(0xFF4A0D2A),
            accent = Color(0xFFDE7515),
            onAccent = Color(0xFF151515),
            background = Color(0xFFFFFFFF),
            surface = Color(0xFFFFF8FB),
            onSurface = Color(0xFF24161C),
            outline = Color(0xFFEADDE3),
        ),
    )
}
